# Generated by Django 6.0 on 2026-04-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
