# Generated by Django 6.0.3 on 2026-04-29 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
    ]
